name: "Publish Release"
on:
  release:
    types: [published]
jobs:
  publish:
    uses: t15i/workflows/.github/workflows/nodejs-lib-release.yml@main
    with: 
      branch: ${{ github.event.repository.default_branch }}
      tag: ${{ github.event.release.tag_name }}
    secrets:
      RELEASE_BOT_ID: ${{ secrets.RELEASE_BOT_ID }}
      RELEASE_BOT_PRIVATE_KEY: ${{ secrets.RELEASE_BOT_PRIVATE_KEY }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
